/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     *   Required Roles: Admin  Rate limit default: 10 Requests / 60000 ms TTL
     * Re-evaluate the drop chunks cache; partitions the open chunk into new subchunks if big enough
     */
    async getNextDropRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/admin`,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     *   Required Roles: Admin  Rate limit default: 10 Requests / 60000 ms TTL
     * Re-evaluate the drop chunks cache; partitions the open chunk into new subchunks if big enough
     */
    async getNextDrop(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getNextDropRaw(initOverrides);
    }

}
