/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  RegistrationRequest,
  TokenResponse,
} from '../models/index';
import {
    RegistrationRequestFromJSON,
    RegistrationRequestToJSON,
    TokenResponseFromJSON,
    TokenResponseToJSON,
} from '../models/index';

export interface GetAccessTokenRequest {
    code: string;
}

export interface RegisterDiscordUserRequest {
    registrationRequest: RegistrationRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     *   Required Roles: None  Rate limit default: 10 Requests / 60000 ms TTL
     * Get the access token for a discord user with given oauth2 auth code
     */
    async getAccessTokenRaw(requestParameters: GetAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling getAccessToken().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/token`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     *   Required Roles: None  Rate limit default: 10 Requests / 60000 ms TTL
     * Get the access token for a discord user with given oauth2 auth code
     */
    async getAccessToken(requestParameters: GetAccessTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.getAccessTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *   Required Roles: None  Rate limit default: 10 Requests / 60000 ms TTL
     * Create a palantir account for a discord user with given oauth2 auth code
     */
    async registerDiscordUserRaw(requestParameters: RegisterDiscordUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenResponse>> {
        if (requestParameters['registrationRequest'] == null) {
            throw new runtime.RequiredError(
                'registrationRequest',
                'Required parameter "registrationRequest" was null or undefined when calling registerDiscordUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegistrationRequestToJSON(requestParameters['registrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenResponseFromJSON(jsonValue));
    }

    /**
     *   Required Roles: None  Rate limit default: 10 Requests / 60000 ms TTL
     * Create a palantir account for a discord user with given oauth2 auth code
     */
    async registerDiscordUser(requestParameters: RegisterDiscordUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenResponse> {
        const response = await this.registerDiscordUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
