/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DropDto,
  LobbiesResponseDto,
  LobbyLinkDto,
} from '../models/index';
import {
    DropDtoFromJSON,
    DropDtoToJSON,
    LobbiesResponseDtoFromJSON,
    LobbiesResponseDtoToJSON,
    LobbyLinkDtoFromJSON,
    LobbyLinkDtoToJSON,
} from '../models/index';

export interface GetDecryptedLobbyLinkRequest {
    token: string;
}

export interface GetLobbyDropsRequest {
    token: string;
}

/**
 * 
 */
export class LobbiesApi extends runtime.BaseAPI {

    /**
     *   Required Roles: Member  Rate limit default: 10 Requests / 60000 ms TTL
     * Redirect to a lobby
     */
    async getDecryptedLobbyLinkRaw(requestParameters: GetDecryptedLobbyLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LobbyLinkDto>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling getDecryptedLobbyLink().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/lobbies/join/{token}`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LobbyLinkDtoFromJSON(jsonValue));
    }

    /**
     *   Required Roles: Member  Rate limit default: 10 Requests / 60000 ms TTL
     * Redirect to a lobby
     */
    async getDecryptedLobbyLink(requestParameters: GetDecryptedLobbyLinkRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LobbyLinkDto> {
        const response = await this.getDecryptedLobbyLinkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *   Required Roles: Moderator  Rate limit default: 10 Requests / 60000 ms TTL
     * Get all drops caught in a lobby
     */
    async getLobbyDropsRaw(requestParameters: GetLobbyDropsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DropDto>>> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling getLobbyDrops().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/lobbies/{token}/drops`.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DropDtoFromJSON));
    }

    /**
     *   Required Roles: Moderator  Rate limit default: 10 Requests / 60000 ms TTL
     * Get all drops caught in a lobby
     */
    async getLobbyDrops(requestParameters: GetLobbyDropsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DropDto>> {
        const response = await this.getLobbyDropsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     *   Required Roles: Moderator  Rate limit default: 30 Requests / 60000 ms TTL
     * Get all present lobbies
     */
    async inspectAllLobbiesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<LobbiesResponseDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/lobbies`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(LobbiesResponseDtoFromJSON));
    }

    /**
     *   Required Roles: Moderator  Rate limit default: 30 Requests / 60000 ms TTL
     * Get all present lobbies
     */
    async inspectAllLobbies(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<LobbiesResponseDto>> {
        const response = await this.inspectAllLobbiesRaw(initOverrides);
        return await response.value();
    }

}
