/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SceneDto,
} from '../models/index';
import {
    SceneDtoFromJSON,
    SceneDtoToJSON,
} from '../models/index';

export interface GetSceneByIdRequest {
    id: number;
}

/**
 * 
 */
export class ScenesApi extends runtime.BaseAPI {

    /**
     *   Required Roles: None  Rate limit default: 10 Requests / 60000 ms TTL
     * Get all scenes
     */
    async getAllScenesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SceneDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/scenes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SceneDtoFromJSON));
    }

    /**
     *   Required Roles: None  Rate limit default: 10 Requests / 60000 ms TTL
     * Get all scenes
     */
    async getAllScenes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SceneDto>> {
        const response = await this.getAllScenesRaw(initOverrides);
        return await response.value();
    }

    /**
     *   Required Roles: None  Rate limit default: 10 Requests / 60000 ms TTL
     * Get a scene by ID
     */
    async getSceneByIdRaw(requestParameters: GetSceneByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SceneDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSceneById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/scenes/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SceneDtoFromJSON(jsonValue));
    }

    /**
     *   Required Roles: None  Rate limit default: 10 Requests / 60000 ms TTL
     * Get a scene by ID
     */
    async getSceneById(requestParameters: GetSceneByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SceneDto> {
        const response = await this.getSceneByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
