/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { IGuildLobbiesHub, ILobbyHub, IOnlineItemsHub, IGuildLobbiesReceiver, ILobbyReceiver, IOnlineItemsReceiver } from './tobeh.Avallone.Server.Hubs.Interfaces';
import type { GuildLobbiesUpdatedDto, LobbyDiscoveredDto, TypoLobbyStateDto, SkribblLobbyStateDto, SkribblLobbyTypoSettingsUpdateDto, DropClaimDto, DropClaimResultDto, AwardGiftDto, TypoLobbySettingsDto, DropAnnouncementDto, AwardGiftedDto, DropClearDto, OnlineItemsUpdatedDto } from '../tobeh.Avallone.Server.Classes.Dto';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "IGuildLobbiesHub"): HubProxyFactory<IGuildLobbiesHub>;
    (hubType: "ILobbyHub"): HubProxyFactory<ILobbyHub>;
    (hubType: "IOnlineItemsHub"): HubProxyFactory<IOnlineItemsHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "IGuildLobbiesHub") {
        return IGuildLobbiesHub_HubProxyFactory.Instance;
    }
    if(hubType === "ILobbyHub") {
        return ILobbyHub_HubProxyFactory.Instance;
    }
    if(hubType === "IOnlineItemsHub") {
        return IOnlineItemsHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "IGuildLobbiesReceiver"): ReceiverRegister<IGuildLobbiesReceiver>;
    (receiverType: "ILobbyReceiver"): ReceiverRegister<ILobbyReceiver>;
    (receiverType: "IOnlineItemsReceiver"): ReceiverRegister<IOnlineItemsReceiver>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "IGuildLobbiesReceiver") {
        return IGuildLobbiesReceiver_Binder.Instance;
    }
    if(receiverType === "ILobbyReceiver") {
        return ILobbyReceiver_Binder.Instance;
    }
    if(receiverType === "IOnlineItemsReceiver") {
        return IOnlineItemsReceiver_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class IGuildLobbiesHub_HubProxyFactory implements HubProxyFactory<IGuildLobbiesHub> {
    public static Instance = new IGuildLobbiesHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): IGuildLobbiesHub => {
        return new IGuildLobbiesHub_HubProxy(connection);
    }
}

class IGuildLobbiesHub_HubProxy implements IGuildLobbiesHub {

    public constructor(private connection: HubConnection) {
    }

    public readonly subscribeGuildLobbies = async (guildId: string): Promise<GuildLobbiesUpdatedDto> => {
        return await this.connection.invoke("SubscribeGuildLobbies", guildId);
    }
}

class ILobbyHub_HubProxyFactory implements HubProxyFactory<ILobbyHub> {
    public static Instance = new ILobbyHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): ILobbyHub => {
        return new ILobbyHub_HubProxy(connection);
    }
}

class ILobbyHub_HubProxy implements ILobbyHub {

    public constructor(private connection: HubConnection) {
    }

    public readonly lobbyDiscovered = async (lobbyDiscovery: LobbyDiscoveredDto): Promise<TypoLobbyStateDto> => {
        return await this.connection.invoke("LobbyDiscovered", lobbyDiscovery);
    }

    public readonly claimLobbyOwnership = async (): Promise<void> => {
        return await this.connection.invoke("ClaimLobbyOwnership");
    }

    public readonly updateSkribblLobbyState = async (state: SkribblLobbyStateDto): Promise<void> => {
        return await this.connection.invoke("UpdateSkribblLobbyState", state);
    }

    public readonly updateTypoLobbySettings = async (typoSettings: SkribblLobbyTypoSettingsUpdateDto): Promise<void> => {
        return await this.connection.invoke("UpdateTypoLobbySettings", typoSettings);
    }

    public readonly claimDrop = async (dropClaim: DropClaimDto): Promise<DropClaimResultDto> => {
        return await this.connection.invoke("ClaimDrop", dropClaim);
    }

    public readonly giftAward = async (awardGift: AwardGiftDto): Promise<void> => {
        return await this.connection.invoke("GiftAward", awardGift);
    }
}

class IOnlineItemsHub_HubProxyFactory implements HubProxyFactory<IOnlineItemsHub> {
    public static Instance = new IOnlineItemsHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): IOnlineItemsHub => {
        return new IOnlineItemsHub_HubProxy(connection);
    }
}

class IOnlineItemsHub_HubProxy implements IOnlineItemsHub {

    public constructor(private connection: HubConnection) {
    }
}


// Receiver

class IGuildLobbiesReceiver_Binder implements ReceiverRegister<IGuildLobbiesReceiver> {

    public static Instance = new IGuildLobbiesReceiver_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: IGuildLobbiesReceiver): Disposable => {

        const __guildLobbiesUpdated = (...args: [GuildLobbiesUpdatedDto]) => receiver.guildLobbiesUpdated(...args);

        connection.on("GuildLobbiesUpdated", __guildLobbiesUpdated);

        const methodList: ReceiverMethod[] = [
            { methodName: "GuildLobbiesUpdated", method: __guildLobbiesUpdated }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

class ILobbyReceiver_Binder implements ReceiverRegister<ILobbyReceiver> {

    public static Instance = new ILobbyReceiver_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: ILobbyReceiver): Disposable => {

        const __typoLobbySettingsUpdated = (...args: [TypoLobbySettingsDto]) => receiver.typoLobbySettingsUpdated(...args);
        const __lobbyOwnershipResigned = () => receiver.lobbyOwnershipResigned();
        const __dropAnnounced = (...args: [DropAnnouncementDto]) => receiver.dropAnnounced(...args);
        const __awardGifted = (...args: [AwardGiftedDto]) => receiver.awardGifted(...args);
        const __dropClaimed = (...args: [DropClaimResultDto]) => receiver.dropClaimed(...args);
        const __dropCleared = (...args: [DropClearDto]) => receiver.dropCleared(...args);

        connection.on("TypoLobbySettingsUpdated", __typoLobbySettingsUpdated);
        connection.on("LobbyOwnershipResigned", __lobbyOwnershipResigned);
        connection.on("DropAnnounced", __dropAnnounced);
        connection.on("AwardGifted", __awardGifted);
        connection.on("DropClaimed", __dropClaimed);
        connection.on("DropCleared", __dropCleared);

        const methodList: ReceiverMethod[] = [
            { methodName: "TypoLobbySettingsUpdated", method: __typoLobbySettingsUpdated },
            { methodName: "LobbyOwnershipResigned", method: __lobbyOwnershipResigned },
            { methodName: "DropAnnounced", method: __dropAnnounced },
            { methodName: "AwardGifted", method: __awardGifted },
            { methodName: "DropClaimed", method: __dropClaimed },
            { methodName: "DropCleared", method: __dropCleared }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

class IOnlineItemsReceiver_Binder implements ReceiverRegister<IOnlineItemsReceiver> {

    public static Instance = new IOnlineItemsReceiver_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: IOnlineItemsReceiver): Disposable => {

        const __onlineItemsUpdated = (...args: [OnlineItemsUpdatedDto]) => receiver.onlineItemsUpdated(...args);

        connection.on("OnlineItemsUpdated", __onlineItemsUpdated);

        const methodList: ReceiverMethod[] = [
            { methodName: "OnlineItemsUpdated", method: __onlineItemsUpdated }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

