/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.AwardGiftDto */
export type AwardGiftDto = {
    /** Transpiled from int */
    awardInventoryId: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.AwardGiftedDto */
export type AwardGiftedDto = {
    /** Transpiled from int */
    receiverLobbyPlayerId: number;
    /** Transpiled from int */
    awarderLobbyPlayerId: number;
    /** Transpiled from int */
    awardInventoryId: number;
    /** Transpiled from int */
    awardId: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.DropAnnouncementDto */
export type DropAnnouncementDto = {
    /** Transpiled from long */
    dropId: number;
    /** Transpiled from int */
    eventDropId?: number;
    /** Transpiled from int */
    position: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.DropClaimDto */
export type DropClaimDto = {
    /** Transpiled from long */
    dropId: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.DropClaimResultDto */
export type DropClaimResultDto = {
    /** Transpiled from string */
    username: string;
    /** Transpiled from bool */
    firstClaim: boolean;
    /** Transpiled from bool */
    clearedDrop: boolean;
    /** Transpiled from int */
    catchTime: number;
    /** Transpiled from double */
    leagueWeight: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.GuildLobbiesUpdatedDto */
export type GuildLobbiesUpdatedDto = {
    /** Transpiled from string */
    guildId: string;
    /** Transpiled from System.Collections.Generic.List<tobeh.Avallone.Server.Classes.Dto.GuildLobbyDto> */
    lobbies: GuildLobbyDto[];
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.GuildLobbyDto */
export type GuildLobbyDto = {
    /** Transpiled from string */
    userName: string;
    /** Transpiled from int */
    currentPlayers: number;
    /** Transpiled from string */
    language: string;
    /** Transpiled from string */
    invite: string;
    /** Transpiled from bool */
    private: boolean;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.LobbyDiscoveredDto */
export type LobbyDiscoveredDto = {
    /** Transpiled from tobeh.Avallone.Server.Classes.Dto.SkribblLobbyStateDto */
    lobby: SkribblLobbyStateDto;
    /** Transpiled from string? */
    ownerClaimToken?: string;
    /** Transpiled from int */
    playerId: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.TypoLobbySettingsDto */
export type TypoLobbySettingsDto = {
    /** Transpiled from string */
    description: string;
    /** Transpiled from bool */
    whitelistAllowedServers: boolean;
    /** Transpiled from System.Collections.Generic.List<string> */
    allowedServers: string[];
    /** Transpiled from long */
    lobbyOwnershipClaim?: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.TypoLobbyStateDto */
export type TypoLobbyStateDto = {
    /** Transpiled from bool */
    playerIsOwner: boolean;
    /** Transpiled from string */
    ownershipClaimToken: string;
    /** Transpiled from string */
    lobbyId: string;
    /** Transpiled from long */
    ownershipClaim: number;
    /** Transpiled from tobeh.Avallone.Server.Classes.Dto.TypoLobbySettingsDto */
    lobbySettings: TypoLobbySettingsDto;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.SkribblLobbyPlayerDto */
export type SkribblLobbyPlayerDto = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from int */
    playerId: number;
    /** Transpiled from int */
    score: number;
    /** Transpiled from bool */
    isDrawing: boolean;
    /** Transpiled from bool */
    hasGuessed: boolean;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.SkribblLobbySettingsDto */
export type SkribblLobbySettingsDto = {
    /** Transpiled from string */
    language: string;
    /** Transpiled from int */
    players: number;
    /** Transpiled from int */
    drawTime: number;
    /** Transpiled from int */
    rounds: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.SkribblLobbyStateDto */
export type SkribblLobbyStateDto = {
    /** Transpiled from string */
    link: string;
    /** Transpiled from int */
    ownerId?: number;
    /** Transpiled from int */
    round: number;
    /** Transpiled from System.Collections.Generic.List<tobeh.Avallone.Server.Classes.Dto.SkribblLobbyPlayerDto> */
    players: SkribblLobbyPlayerDto[];
    /** Transpiled from tobeh.Avallone.Server.Classes.Dto.SkribblLobbySettingsDto */
    settings: SkribblLobbySettingsDto;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.LobbyStateDto */
export type LobbyStateDto = {
    /** Transpiled from tobeh.Avallone.Server.Classes.Dto.SkribblLobbyStateDto */
    skribblState: SkribblLobbyStateDto;
    /** Transpiled from tobeh.Avallone.Server.Classes.Dto.TypoLobbyStateDto */
    typoState: TypoLobbyStateDto;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.MemberDto */
export type MemberDto = {
    /** Transpiled from string */
    username: string;
    /** Transpiled from int */
    login: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.OnlineItemsUpdatedDto */
export type OnlineItemsUpdatedDto = {
    /** Transpiled from System.Collections.Generic.List<tobeh.Avallone.Server.Classes.Dto.OnlineItemDto> */
    items: OnlineItemDto[];
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.OnlineItemDto */
export type OnlineItemDto = {
    /** Transpiled from tobeh.Avallone.Server.Classes.Dto.OnlineItemTypeDto */
    type: OnlineItemTypeDto;
    /** Transpiled from int */
    slot: number;
    /** Transpiled from int */
    itemId: number;
    /** Transpiled from string */
    lobbyKey: string;
    /** Transpiled from int */
    lobbyPlayerId: number;
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.OnlineItemTypeDto */
export enum OnlineItemTypeDto {
    Award = 3,
    Sprite = 0,
    SpriteShift = 1,
    Scene = 2,
    SceneTheme = 6,
    Rewardee = 5,
}

/** Transpiled from tobeh.Avallone.Server.Classes.Dto.SkribblLobbyTypoSettingsUpdateDto */
export type SkribblLobbyTypoSettingsUpdateDto = {
    /** Transpiled from bool */
    whitelistAllowedServers: boolean;
    /** Transpiled from System.Collections.Generic.List<string> */
    allowedServers: string[];
    /** Transpiled from string */
    description: string;
}

