/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessTokenDto
 */
export interface AccessTokenDto {
    /**
     * The access token of an user
     * @type {string}
     * @memberof AccessTokenDto
     */
    token: string;
}

/**
 * Check if a given object implements the AccessTokenDto interface.
 */
export function instanceOfAccessTokenDto(value: object): value is AccessTokenDto {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AccessTokenDtoFromJSON(json: any): AccessTokenDto {
    return AccessTokenDtoFromJSONTyped(json, false);
}

export function AccessTokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTokenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['Token'],
    };
}

export function AccessTokenDtoToJSON(value?: AccessTokenDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Token': value['token'],
    };
}

