/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AwardDto } from './AwardDto';
import {
    AwardDtoFromJSON,
    AwardDtoFromJSONTyped,
    AwardDtoToJSON,
    AwardDtoToJSONTyped,
} from './AwardDto';

/**
 * 
 * @export
 * @interface AwardInventoryDto
 */
export interface AwardInventoryDto {
    /**
     * The award type
     * @type {AwardDto}
     * @memberof AwardInventoryDto
     */
    award: AwardDto;
    /**
     * The award inventory ids of this award type
     * @type {Array<number>}
     * @memberof AwardInventoryDto
     */
    inventoryIds: Array<number>;
}

/**
 * Check if a given object implements the AwardInventoryDto interface.
 */
export function instanceOfAwardInventoryDto(value: object): value is AwardInventoryDto {
    if (!('award' in value) || value['award'] === undefined) return false;
    if (!('inventoryIds' in value) || value['inventoryIds'] === undefined) return false;
    return true;
}

export function AwardInventoryDtoFromJSON(json: any): AwardInventoryDto {
    return AwardInventoryDtoFromJSONTyped(json, false);
}

export function AwardInventoryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwardInventoryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'award': AwardDtoFromJSON(json['award']),
        'inventoryIds': json['inventoryIds'],
    };
}

export function AwardInventoryDtoToJSON(json: any): AwardInventoryDto {
    return AwardInventoryDtoToJSONTyped(json, false);
}

export function AwardInventoryDtoToJSONTyped(value?: AwardInventoryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'award': AwardDtoToJSON(value['award']),
        'inventoryIds': value['inventoryIds'],
    };
}

