/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloudSearchDto
 */
export interface CloudSearchDto {
    /**
     * The size of a single search result page
     * @type {number}
     * @memberof CloudSearchDto
     */
    pageSize: number;
    /**
     * The current pagination index for given search criteria
     * @type {number}
     * @memberof CloudSearchDto
     */
    page: number;
    /**
     * Exact name of the author
     * @type {string}
     * @memberof CloudSearchDto
     */
    authorQuery?: string;
    /**
     * Exact language of the lobby
     * @type {string}
     * @memberof CloudSearchDto
     */
    languageQuery?: string;
    /**
     * Oldest creation date filter
     * @type {string}
     * @memberof CloudSearchDto
     */
    createdBeforeQuery?: string;
    /**
     * Most recent creation date filter
     * @type {string}
     * @memberof CloudSearchDto
     */
    createdAfterQuery?: string;
    /**
     * Filter for private lobbies
     * @type {boolean}
     * @memberof CloudSearchDto
     */
    createdInPrivateLobbyQuery?: boolean;
    /**
     * Filter for own drawings
     * @type {boolean}
     * @memberof CloudSearchDto
     */
    isOwnQuery?: boolean;
    /**
     * Exact title of the drawing
     * @type {string}
     * @memberof CloudSearchDto
     */
    titleQuery?: string;
}

/**
 * Check if a given object implements the CloudSearchDto interface.
 */
export function instanceOfCloudSearchDto(value: object): value is CloudSearchDto {
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    return true;
}

export function CloudSearchDtoFromJSON(json: any): CloudSearchDto {
    return CloudSearchDtoFromJSONTyped(json, false);
}

export function CloudSearchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudSearchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'pageSize': json['pageSize'],
        'page': json['page'],
        'authorQuery': json['authorQuery'] == null ? undefined : json['authorQuery'],
        'languageQuery': json['languageQuery'] == null ? undefined : json['languageQuery'],
        'createdBeforeQuery': json['createdBeforeQuery'] == null ? undefined : json['createdBeforeQuery'],
        'createdAfterQuery': json['createdAfterQuery'] == null ? undefined : json['createdAfterQuery'],
        'createdInPrivateLobbyQuery': json['createdInPrivateLobbyQuery'] == null ? undefined : json['createdInPrivateLobbyQuery'],
        'isOwnQuery': json['isOwnQuery'] == null ? undefined : json['isOwnQuery'],
        'titleQuery': json['titleQuery'] == null ? undefined : json['titleQuery'],
    };
}

export function CloudSearchDtoToJSON(value?: CloudSearchDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'pageSize': value['pageSize'],
        'page': value['page'],
        'authorQuery': value['authorQuery'],
        'languageQuery': value['languageQuery'],
        'createdBeforeQuery': value['createdBeforeQuery'],
        'createdAfterQuery': value['createdAfterQuery'],
        'createdInPrivateLobbyQuery': value['createdInPrivateLobbyQuery'],
        'isOwnQuery': value['isOwnQuery'],
        'titleQuery': value['titleQuery'],
    };
}

