/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloudImageDto
 */
export interface CloudImageDto {
    /**
     * Image name
     * @type {string}
     * @memberof CloudImageDto
     */
    name: string;
    /**
     * Image author
     * @type {string}
     * @memberof CloudImageDto
     */
    author: string;
    /**
     * Image creation timestamp ms
     * @type {string}
     * @memberof CloudImageDto
     */
    createdAt: string;
    /**
     * Image Id
     * @type {string}
     * @memberof CloudImageDto
     */
    id: string;
    /**
     * Meta Url
     * @type {string}
     * @memberof CloudImageDto
     */
    metaUrl: string;
    /**
     * Draw commands Url
     * @type {string}
     * @memberof CloudImageDto
     */
    commandsUrl: string;
    /**
     * Image Url
     * @type {string}
     * @memberof CloudImageDto
     */
    imageUrl: string;
}

/**
 * Check if a given object implements the CloudImageDto interface.
 */
export function instanceOfCloudImageDto(value: object): value is CloudImageDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('metaUrl' in value) || value['metaUrl'] === undefined) return false;
    if (!('commandsUrl' in value) || value['commandsUrl'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    return true;
}

export function CloudImageDtoFromJSON(json: any): CloudImageDto {
    return CloudImageDtoFromJSONTyped(json, false);
}

export function CloudImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudImageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'author': json['author'],
        'createdAt': json['createdAt'],
        'id': json['id'],
        'metaUrl': json['metaUrl'],
        'commandsUrl': json['commandsUrl'],
        'imageUrl': json['imageUrl'],
    };
}

export function CloudImageDtoToJSON(value?: CloudImageDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'author': value['author'],
        'createdAt': value['createdAt'],
        'id': value['id'],
        'metaUrl': value['metaUrl'],
        'commandsUrl': value['commandsUrl'],
        'imageUrl': value['imageUrl'],
    };
}

