/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloudDeleteDto
 */
export interface CloudDeleteDto {
    /**
     * Ids that will be removed from the cloud
     * @type {Array<string>}
     * @memberof CloudDeleteDto
     */
    ids: Array<string>;
}

/**
 * Check if a given object implements the CloudDeleteDto interface.
 */
export function instanceOfCloudDeleteDto(value: object): value is CloudDeleteDto {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function CloudDeleteDtoFromJSON(json: any): CloudDeleteDto {
    return CloudDeleteDtoFromJSONTyped(json, false);
}

export function CloudDeleteDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudDeleteDto {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

export function CloudDeleteDtoToJSON(json: any): CloudDeleteDto {
    return CloudDeleteDtoToJSONTyped(json, false);
}

export function CloudDeleteDtoToJSONTyped(value?: CloudDeleteDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

