/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CloudUploadedDto
 */
export interface CloudUploadedDto {
    /**
     * ID of the uploaded image
     * @type {string}
     * @memberof CloudUploadedDto
     */
    id: string;
}

/**
 * Check if a given object implements the CloudUploadedDto interface.
 */
export function instanceOfCloudUploadedDto(value: object): value is CloudUploadedDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CloudUploadedDtoFromJSON(json: any): CloudUploadedDto {
    return CloudUploadedDtoFromJSONTyped(json, false);
}

export function CloudUploadedDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudUploadedDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CloudUploadedDtoToJSON(json: any): CloudUploadedDto {
    return CloudUploadedDtoToJSONTyped(json, false);
}

export function CloudUploadedDtoToJSONTyped(value?: CloudUploadedDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

