/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmojiCandidateDto
 */
export interface EmojiCandidateDto {
    /**
     * Emoji name
     * @type {string}
     * @memberof EmojiCandidateDto
     */
    name: string;
    /**
     * Emoji url
     * @type {string}
     * @memberof EmojiCandidateDto
     */
    url: string;
    /**
     * Whether emoji is animated or static
     * @type {boolean}
     * @memberof EmojiCandidateDto
     */
    animated: boolean;
}

/**
 * Check if a given object implements the EmojiCandidateDto interface.
 */
export function instanceOfEmojiCandidateDto(value: object): value is EmojiCandidateDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('animated' in value) || value['animated'] === undefined) return false;
    return true;
}

export function EmojiCandidateDtoFromJSON(json: any): EmojiCandidateDto {
    return EmojiCandidateDtoFromJSONTyped(json, false);
}

export function EmojiCandidateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmojiCandidateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'url': json['url'],
        'animated': json['animated'],
    };
}

export function EmojiCandidateDtoToJSON(value?: EmojiCandidateDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'url': value['url'],
        'animated': value['animated'],
    };
}

