/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GuildDto
 */
export interface GuildDto {
    /**
     * The guild's ID
     * @type {string}
     * @memberof GuildDto
     */
    guildID: string;
    /**
     * The guild's Palantir token
     * @type {number}
     * @memberof GuildDto
     */
    invite: number;
    /**
     * The guild's name
     * @type {string}
     * @memberof GuildDto
     */
    guildName: string;
}

/**
 * Check if a given object implements the GuildDto interface.
 */
export function instanceOfGuildDto(value: object): value is GuildDto {
    if (!('guildID' in value) || value['guildID'] === undefined) return false;
    if (!('invite' in value) || value['invite'] === undefined) return false;
    if (!('guildName' in value) || value['guildName'] === undefined) return false;
    return true;
}

export function GuildDtoFromJSON(json: any): GuildDto {
    return GuildDtoFromJSONTyped(json, false);
}

export function GuildDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GuildDto {
    if (json == null) {
        return json;
    }
    return {
        
        'guildID': json['GuildID'],
        'invite': json['Invite'],
        'guildName': json['GuildName'],
    };
}

export function GuildDtoToJSON(value?: GuildDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'GuildID': value['guildID'],
        'Invite': value['invite'],
        'GuildName': value['guildName'],
    };
}

