/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeagueCountRanking
 */
export interface LeagueCountRanking {
    /**
     * The palantir username of the participant
     * @type {string}
     * @memberof LeagueCountRanking
     */
    name: string;
    /**
     * Amount of league drops collected
     * @type {number}
     * @memberof LeagueCountRanking
     */
    caughtDrops: number;
}

/**
 * Check if a given object implements the LeagueCountRanking interface.
 */
export function instanceOfLeagueCountRanking(value: object): value is LeagueCountRanking {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('caughtDrops' in value) || value['caughtDrops'] === undefined) return false;
    return true;
}

export function LeagueCountRankingFromJSON(json: any): LeagueCountRanking {
    return LeagueCountRankingFromJSONTyped(json, false);
}

export function LeagueCountRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeagueCountRanking {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'caughtDrops': json['caughtDrops'],
    };
}

export function LeagueCountRankingToJSON(value?: LeagueCountRanking | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'caughtDrops': value['caughtDrops'],
    };
}

