/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeagueAverageTimeRanking
 */
export interface LeagueAverageTimeRanking {
    /**
     * The palantir username of the participant
     * @type {string}
     * @memberof LeagueAverageTimeRanking
     */
    name: string;
    /**
     * The average catch response time of all caught league drops
     * @type {number}
     * @memberof LeagueAverageTimeRanking
     */
    averageTime: number;
}

/**
 * Check if a given object implements the LeagueAverageTimeRanking interface.
 */
export function instanceOfLeagueAverageTimeRanking(value: object): value is LeagueAverageTimeRanking {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('averageTime' in value) || value['averageTime'] === undefined) return false;
    return true;
}

export function LeagueAverageTimeRankingFromJSON(json: any): LeagueAverageTimeRanking {
    return LeagueAverageTimeRankingFromJSONTyped(json, false);
}

export function LeagueAverageTimeRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeagueAverageTimeRanking {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'averageTime': json['averageTime'],
    };
}

export function LeagueAverageTimeRankingToJSON(value?: LeagueAverageTimeRanking | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'averageTime': value['averageTime'],
    };
}

