/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeagueScoreRanking
 */
export interface LeagueScoreRanking {
    /**
     * The palantir username of the participant
     * @type {string}
     * @memberof LeagueScoreRanking
     */
    name: string;
    /**
     * Sum of the weighted scores of each league drop
     * @type {number}
     * @memberof LeagueScoreRanking
     */
    score: number;
}

/**
 * Check if a given object implements the LeagueScoreRanking interface.
 */
export function instanceOfLeagueScoreRanking(value: object): value is LeagueScoreRanking {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function LeagueScoreRankingFromJSON(json: any): LeagueScoreRanking {
    return LeagueScoreRankingFromJSONTyped(json, false);
}

export function LeagueScoreRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeagueScoreRanking {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'score': json['score'],
    };
}

export function LeagueScoreRankingToJSON(value?: LeagueScoreRanking | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'score': value['score'],
    };
}

