/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeagueAverageWeightRanking
 */
export interface LeagueAverageWeightRanking {
    /**
     * The palantir username of the participant
     * @type {string}
     * @memberof LeagueAverageWeightRanking
     */
    name: string;
    /**
     * The average of weighted value of all caught league drops
     * @type {number}
     * @memberof LeagueAverageWeightRanking
     */
    averageWeight: number;
}

/**
 * Check if a given object implements the LeagueAverageWeightRanking interface.
 */
export function instanceOfLeagueAverageWeightRanking(value: object): value is LeagueAverageWeightRanking {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('averageWeight' in value) || value['averageWeight'] === undefined) return false;
    return true;
}

export function LeagueAverageWeightRankingFromJSON(json: any): LeagueAverageWeightRanking {
    return LeagueAverageWeightRankingFromJSONTyped(json, false);
}

export function LeagueAverageWeightRankingFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeagueAverageWeightRanking {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'averageWeight': json['averageWeight'],
    };
}

export function LeagueAverageWeightRankingToJSON(value?: LeagueAverageWeightRanking | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'averageWeight': value['averageWeight'],
    };
}

