/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PalantirLobbyPlayerDto } from './PalantirLobbyPlayerDto';
import {
    PalantirLobbyPlayerDtoFromJSON,
    PalantirLobbyPlayerDtoFromJSONTyped,
    PalantirLobbyPlayerDtoToJSON,
} from './PalantirLobbyPlayerDto';
import type { LobbyDetailsDto } from './LobbyDetailsDto';
import {
    LobbyDetailsDtoFromJSON,
    LobbyDetailsDtoFromJSONTyped,
    LobbyDetailsDtoToJSON,
} from './LobbyDetailsDto';
import type { PalantirLobbyDto } from './PalantirLobbyDto';
import {
    PalantirLobbyDtoFromJSON,
    PalantirLobbyDtoFromJSONTyped,
    PalantirLobbyDtoToJSON,
} from './PalantirLobbyDto';

/**
 * 
 * @export
 * @interface LobbiesResponseDto
 */
export interface LobbiesResponseDto {
    /**
     * Lobby palantir details
     * @type {PalantirLobbyDto}
     * @memberof LobbiesResponseDto
     */
    lobby: PalantirLobbyDto;
    /**
     * Lobby skribbl details
     * @type {LobbyDetailsDto}
     * @memberof LobbiesResponseDto
     */
    details: LobbyDetailsDto;
    /**
     * Lobby palantir players
     * @type {Array<PalantirLobbyPlayerDto>}
     * @memberof LobbiesResponseDto
     */
    players: Array<PalantirLobbyPlayerDto>;
}

/**
 * Check if a given object implements the LobbiesResponseDto interface.
 */
export function instanceOfLobbiesResponseDto(value: object): value is LobbiesResponseDto {
    if (!('lobby' in value) || value['lobby'] === undefined) return false;
    if (!('details' in value) || value['details'] === undefined) return false;
    if (!('players' in value) || value['players'] === undefined) return false;
    return true;
}

export function LobbiesResponseDtoFromJSON(json: any): LobbiesResponseDto {
    return LobbiesResponseDtoFromJSONTyped(json, false);
}

export function LobbiesResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbiesResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lobby': PalantirLobbyDtoFromJSON(json['lobby']),
        'details': LobbyDetailsDtoFromJSON(json['details']),
        'players': ((json['players'] as Array<any>).map(PalantirLobbyPlayerDtoFromJSON)),
    };
}

export function LobbiesResponseDtoToJSON(value?: LobbiesResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'lobby': PalantirLobbyDtoToJSON(value['lobby']),
        'details': LobbyDetailsDtoToJSON(value['details']),
        'players': ((value['players'] as Array<any>).map(PalantirLobbyPlayerDtoToJSON)),
    };
}

