/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LobbyPlayerDto } from './LobbyPlayerDto';
import {
    LobbyPlayerDtoFromJSON,
    LobbyPlayerDtoFromJSONTyped,
    LobbyPlayerDtoToJSON,
} from './LobbyPlayerDto';

/**
 * 
 * @export
 * @interface LobbyDetailsDto
 */
export interface LobbyDetailsDto {
    /**
     * The lobby language
     * @type {string}
     * @memberof LobbyDetailsDto
     */
    language: string;
    /**
     * The lobby link
     * @type {string}
     * @memberof LobbyDetailsDto
     */
    link: string;
    /**
     * Indicator if the lobby is private
     * @type {boolean}
     * @memberof LobbyDetailsDto
     */
    _private: boolean;
    /**
     * The lobby's current round
     * @type {string}
     * @memberof LobbyDetailsDto
     */
    round: string;
    /**
     * The lobby's current round
     * @type {Array<LobbyPlayerDto>}
     * @memberof LobbyDetailsDto
     */
    players: Array<LobbyPlayerDto>;
}

/**
 * Check if a given object implements the LobbyDetailsDto interface.
 */
export function instanceOfLobbyDetailsDto(value: object): value is LobbyDetailsDto {
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('link' in value) || value['link'] === undefined) return false;
    if (!('_private' in value) || value['_private'] === undefined) return false;
    if (!('round' in value) || value['round'] === undefined) return false;
    if (!('players' in value) || value['players'] === undefined) return false;
    return true;
}

export function LobbyDetailsDtoFromJSON(json: any): LobbyDetailsDto {
    return LobbyDetailsDtoFromJSONTyped(json, false);
}

export function LobbyDetailsDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbyDetailsDto {
    if (json == null) {
        return json;
    }
    return {
        
        'language': json['Language'],
        'link': json['Link'],
        '_private': json['Private'],
        'round': json['Round'],
        'players': ((json['Players'] as Array<any>).map(LobbyPlayerDtoFromJSON)),
    };
}

export function LobbyDetailsDtoToJSON(value?: LobbyDetailsDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Language': value['language'],
        'Link': value['link'],
        'Private': value['_private'],
        'Round': value['round'],
        'Players': ((value['players'] as Array<any>).map(LobbyPlayerDtoToJSON)),
    };
}

