/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LobbyLinkDto
 */
export interface LobbyLinkDto {
    /**
     * Link for a lobby
     * @type {string}
     * @memberof LobbyLinkDto
     */
    link: string;
}

/**
 * Check if a given object implements the LobbyLinkDto interface.
 */
export function instanceOfLobbyLinkDto(value: object): value is LobbyLinkDto {
    if (!('link' in value) || value['link'] === undefined) return false;
    return true;
}

export function LobbyLinkDtoFromJSON(json: any): LobbyLinkDto {
    return LobbyLinkDtoFromJSONTyped(json, false);
}

export function LobbyLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbyLinkDto {
    if (json == null) {
        return json;
    }
    return {
        
        'link': json['link'],
    };
}

export function LobbyLinkDtoToJSON(value?: LobbyLinkDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'link': value['link'],
    };
}

