/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LobbyPlayerDto
 */
export interface LobbyPlayerDto {
    /**
     * Player name
     * @type {string}
     * @memberof LobbyPlayerDto
     */
    name: string;
    /**
     * Player score
     * @type {number}
     * @memberof LobbyPlayerDto
     */
    score: number;
    /**
     * Whether the player is the drawer
     * @type {boolean}
     * @memberof LobbyPlayerDto
     */
    drawing: boolean;
    /**
     * Player join ID
     * @type {number}
     * @memberof LobbyPlayerDto
     */
    lobbyPlayerID: number;
}

/**
 * Check if a given object implements the LobbyPlayerDto interface.
 */
export function instanceOfLobbyPlayerDto(value: object): value is LobbyPlayerDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if (!('drawing' in value) || value['drawing'] === undefined) return false;
    if (!('lobbyPlayerID' in value) || value['lobbyPlayerID'] === undefined) return false;
    return true;
}

export function LobbyPlayerDtoFromJSON(json: any): LobbyPlayerDto {
    return LobbyPlayerDtoFromJSONTyped(json, false);
}

export function LobbyPlayerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LobbyPlayerDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['Name'],
        'score': json['Score'],
        'drawing': json['Drawing'],
        'lobbyPlayerID': json['LobbyPlayerID'],
    };
}

export function LobbyPlayerDtoToJSON(value?: LobbyPlayerDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Name': value['name'],
        'Score': value['score'],
        'Drawing': value['drawing'],
        'LobbyPlayerID': value['lobbyPlayerID'],
    };
}

