/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GuildDto } from './GuildDto';
import {
    GuildDtoFromJSON,
    GuildDtoFromJSONTyped,
    GuildDtoToJSON,
} from './GuildDto';

/**
 * 
 * @export
 * @interface MemberWebhookDto
 */
export interface MemberWebhookDto {
    /**
     * The webhook name
     * @type {string}
     * @memberof MemberWebhookDto
     */
    name: string;
    /**
     * The webhook's guild
     * @type {GuildDto}
     * @memberof MemberWebhookDto
     */
    guild: GuildDto;
}

/**
 * Check if a given object implements the MemberWebhookDto interface.
 */
export function instanceOfMemberWebhookDto(value: object): value is MemberWebhookDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('guild' in value) || value['guild'] === undefined) return false;
    return true;
}

export function MemberWebhookDtoFromJSON(json: any): MemberWebhookDto {
    return MemberWebhookDtoFromJSONTyped(json, false);
}

export function MemberWebhookDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberWebhookDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['Name'],
        'guild': GuildDtoFromJSON(json['Guild']),
    };
}

export function MemberWebhookDtoToJSON(value?: MemberWebhookDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Name': value['name'],
        'Guild': GuildDtoToJSON(value['guild']),
    };
}

