/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberSearchDto
 */
export interface MemberSearchDto {
    /**
     * The member's palantir accunt user name
     * @type {string}
     * @memberof MemberSearchDto
     */
    userName: string;
    /**
     * The member's palantir identification
     * @type {string}
     * @memberof MemberSearchDto
     */
    userLogin: string;
    /**
     * The raw database member result
     * @type {object}
     * @memberof MemberSearchDto
     */
    rawMember: object;
}

/**
 * Check if a given object implements the MemberSearchDto interface.
 */
export function instanceOfMemberSearchDto(value: object): value is MemberSearchDto {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('userLogin' in value) || value['userLogin'] === undefined) return false;
    if (!('rawMember' in value) || value['rawMember'] === undefined) return false;
    return true;
}

export function MemberSearchDtoFromJSON(json: any): MemberSearchDto {
    return MemberSearchDtoFromJSONTyped(json, false);
}

export function MemberSearchDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberSearchDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'userLogin': json['userLogin'],
        'rawMember': json['rawMember'],
    };
}

export function MemberSearchDtoToJSON(value?: MemberSearchDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userName': value['userName'],
        'userLogin': value['userLogin'],
        'rawMember': value['rawMember'],
    };
}

