/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PalantirLobbyDto
 */
export interface PalantirLobbyDto {
    /**
     * Lobby description
     * @type {string}
     * @memberof PalantirLobbyDto
     */
    description: string;
    /**
     * Lobby invite encrypted
     * @type {string}
     * @memberof PalantirLobbyDto
     */
    key: string;
    /**
     * Lobby unique id
     * @type {string}
     * @memberof PalantirLobbyDto
     */
    iD: string;
    /**
     * Lobby visibility restriction
     * @type {string}
     * @memberof PalantirLobbyDto
     */
    restriction: string;
}

/**
 * Check if a given object implements the PalantirLobbyDto interface.
 */
export function instanceOfPalantirLobbyDto(value: object): value is PalantirLobbyDto {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('iD' in value) || value['iD'] === undefined) return false;
    if (!('restriction' in value) || value['restriction'] === undefined) return false;
    return true;
}

export function PalantirLobbyDtoFromJSON(json: any): PalantirLobbyDto {
    return PalantirLobbyDtoFromJSONTyped(json, false);
}

export function PalantirLobbyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PalantirLobbyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['Description'],
        'key': json['Key'],
        'iD': json['ID'],
        'restriction': json['Restriction'],
    };
}

export function PalantirLobbyDtoToJSON(value?: PalantirLobbyDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'Description': value['description'],
        'Key': value['key'],
        'ID': value['iD'],
        'Restriction': value['restriction'],
    };
}

