/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrationRequest
 */
export interface RegistrationRequest {
    /**
     * The discord oauth authorization code
     * @type {string}
     * @memberof RegistrationRequest
     */
    code: string;
    /**
     * The flag whether the user wants to conenct to the typo server
     * @type {boolean}
     * @memberof RegistrationRequest
     */
    connectTypo: boolean;
}

/**
 * Check if a given object implements the RegistrationRequest interface.
 */
export function instanceOfRegistrationRequest(value: object): value is RegistrationRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('connectTypo' in value) || value['connectTypo'] === undefined) return false;
    return true;
}

export function RegistrationRequestFromJSON(json: any): RegistrationRequest {
    return RegistrationRequestFromJSONTyped(json, false);
}

export function RegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'connectTypo': json['connectTypo'],
    };
}

export function RegistrationRequestToJSON(value?: RegistrationRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'connectTypo': value['connectTypo'],
    };
}

