/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventDto } from './EventDto';
import {
    EventDtoFromJSON,
    EventDtoFromJSONTyped,
    EventDtoToJSON,
} from './EventDto';

/**
 * 
 * @export
 * @interface SceneDto
 */
export interface SceneDto {
    /**
     * Scene name
     * @type {string}
     * @memberof SceneDto
     */
    name: string;
    /**
     * Scene unique ID
     * @type {number}
     * @memberof SceneDto
     */
    id: number;
    /**
     * Scene url
     * @type {string}
     * @memberof SceneDto
     */
    url: string;
    /**
     * Scene exclusiveness flag, cant be bought regulary or as event scene
     * @type {boolean}
     * @memberof SceneDto
     */
    exclusive: boolean;
    /**
     * Associated event
     * @type {EventDto}
     * @memberof SceneDto
     */
    event?: EventDto;
    /**
     * Primary text color
     * @type {string}
     * @memberof SceneDto
     */
    primaryColor?: string;
    /**
     * Guessed text color
     * @type {string}
     * @memberof SceneDto
     */
    guessedColor?: string;
    /**
     * Scene artist name
     * @type {string}
     * @memberof SceneDto
     */
    artist?: string;
}

/**
 * Check if a given object implements the SceneDto interface.
 */
export function instanceOfSceneDto(value: object): value is SceneDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('exclusive' in value) || value['exclusive'] === undefined) return false;
    return true;
}

export function SceneDtoFromJSON(json: any): SceneDto {
    return SceneDtoFromJSONTyped(json, false);
}

export function SceneDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SceneDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'id': json['id'],
        'url': json['url'],
        'exclusive': json['exclusive'],
        'event': json['event'] == null ? undefined : EventDtoFromJSON(json['event']),
        'primaryColor': json['primaryColor'] == null ? undefined : json['primaryColor'],
        'guessedColor': json['guessedColor'] == null ? undefined : json['guessedColor'],
        'artist': json['artist'] == null ? undefined : json['artist'],
    };
}

export function SceneDtoToJSON(value?: SceneDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'id': value['id'],
        'url': value['url'],
        'exclusive': value['exclusive'],
        'event': EventDtoToJSON(value['event']),
        'primaryColor': value['primaryColor'],
        'guessedColor': value['guessedColor'],
        'artist': value['artist'],
    };
}

