/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SceneThemeDto
 */
export interface SceneThemeDto {
    /**
     * Scene theme name
     * @type {string}
     * @memberof SceneThemeDto
     */
    name: string;
    /**
     * Scene shift identification
     * @type {number}
     * @memberof SceneThemeDto
     */
    shift: number;
}

/**
 * Check if a given object implements the SceneThemeDto interface.
 */
export function instanceOfSceneThemeDto(value: object): value is SceneThemeDto {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('shift' in value) || value['shift'] === undefined) return false;
    return true;
}

export function SceneThemeDtoFromJSON(json: any): SceneThemeDto {
    return SceneThemeDtoFromJSONTyped(json, false);
}

export function SceneThemeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SceneThemeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'shift': json['shift'],
    };
}

export function SceneThemeDtoToJSON(value?: SceneThemeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'shift': value['shift'],
    };
}

