/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SceneInventoryItemDto } from './SceneInventoryItemDto';
import {
    SceneInventoryItemDtoFromJSON,
    SceneInventoryItemDtoFromJSONTyped,
    SceneInventoryItemDtoToJSON,
} from './SceneInventoryItemDto';

/**
 * 
 * @export
 * @interface SetActiveSceneDto
 */
export interface SetActiveSceneDto {
    /**
     * The scene to activate
     * @type {SceneInventoryItemDto}
     * @memberof SetActiveSceneDto
     */
    scene?: SceneInventoryItemDto;
}

/**
 * Check if a given object implements the SetActiveSceneDto interface.
 */
export function instanceOfSetActiveSceneDto(value: object): value is SetActiveSceneDto {
    return true;
}

export function SetActiveSceneDtoFromJSON(json: any): SetActiveSceneDto {
    return SetActiveSceneDtoFromJSONTyped(json, false);
}

export function SetActiveSceneDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetActiveSceneDto {
    if (json == null) {
        return json;
    }
    return {
        
        'scene': json['scene'] == null ? undefined : SceneInventoryItemDtoFromJSON(json['scene']),
    };
}

export function SetActiveSceneDtoToJSON(value?: SetActiveSceneDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'scene': SceneInventoryItemDtoToJSON(value['scene']),
    };
}

