/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpriteSlotDto
 */
export interface SpriteSlotDto {
    /**
     * A sprite slot number, starting at 1
     * @type {number}
     * @memberof SpriteSlotDto
     */
    slotId: number;
    /**
     * The target sprite Id, undefined to use no sprite
     * @type {number}
     * @memberof SpriteSlotDto
     */
    spriteId?: number;
}

/**
 * Check if a given object implements the SpriteSlotDto interface.
 */
export function instanceOfSpriteSlotDto(value: object): value is SpriteSlotDto {
    if (!('slotId' in value) || value['slotId'] === undefined) return false;
    return true;
}

export function SpriteSlotDtoFromJSON(json: any): SpriteSlotDto {
    return SpriteSlotDtoFromJSONTyped(json, false);
}

export function SpriteSlotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpriteSlotDto {
    if (json == null) {
        return json;
    }
    return {
        
        'slotId': json['slotId'],
        'spriteId': json['spriteId'] == null ? undefined : json['spriteId'],
    };
}

export function SpriteSlotDtoToJSON(value?: SpriteSlotDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'slotId': value['slotId'],
        'spriteId': value['spriteId'],
    };
}

