/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SpriteSlotDto } from './SpriteSlotDto';
import {
    SpriteSlotDtoFromJSON,
    SpriteSlotDtoFromJSONTyped,
    SpriteSlotDtoToJSON,
} from './SpriteSlotDto';

/**
 * 
 * @export
 * @interface SpriteComboDto
 */
export interface SpriteComboDto {
    /**
     * The sprite slots that will be the new user sprite combo
     * @type {Array<SpriteSlotDto>}
     * @memberof SpriteComboDto
     */
    slots: Array<SpriteSlotDto>;
}

/**
 * Check if a given object implements the SpriteComboDto interface.
 */
export function instanceOfSpriteComboDto(value: object): value is SpriteComboDto {
    if (!('slots' in value) || value['slots'] === undefined) return false;
    return true;
}

export function SpriteComboDtoFromJSON(json: any): SpriteComboDto {
    return SpriteComboDtoFromJSONTyped(json, false);
}

export function SpriteComboDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpriteComboDto {
    if (json == null) {
        return json;
    }
    return {
        
        'slots': ((json['slots'] as Array<any>).map(SpriteSlotDtoFromJSON)),
    };
}

export function SpriteComboDtoToJSON(value?: SpriteComboDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'slots': ((value['slots'] as Array<any>).map(SpriteSlotDtoToJSON)),
    };
}

