/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemePublishRequestDto
 */
export interface ThemePublishRequestDto {
    /**
     * Creator discord id
     * @type {string}
     * @memberof ThemePublishRequestDto
     */
    owner: string;
}

/**
 * Check if a given object implements the ThemePublishRequestDto interface.
 */
export function instanceOfThemePublishRequestDto(value: object): value is ThemePublishRequestDto {
    if (!('owner' in value) || value['owner'] === undefined) return false;
    return true;
}

export function ThemePublishRequestDtoFromJSON(json: any): ThemePublishRequestDto {
    return ThemePublishRequestDtoFromJSONTyped(json, false);
}

export function ThemePublishRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemePublishRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'owner': json['owner'],
    };
}

export function ThemePublishRequestDtoToJSON(value?: ThemePublishRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'owner': value['owner'],
    };
}

