/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeListingDto
 */
export interface ThemeListingDto {
    /**
     * Public theme id / share
     * @type {string}
     * @memberof ThemeListingDto
     */
    id: string;
    /**
     * Amount of downloads
     * @type {number}
     * @memberof ThemeListingDto
     */
    downloads: number;
    /**
     * Version counter
     * @type {number}
     * @memberof ThemeListingDto
     */
    version: number;
    /**
     * Name of the theme
     * @type {string}
     * @memberof ThemeListingDto
     */
    name: string;
    /**
     * Name of the theme creator
     * @type {string}
     * @memberof ThemeListingDto
     */
    author: string;
}

/**
 * Check if a given object implements the ThemeListingDto interface.
 */
export function instanceOfThemeListingDto(value: object): value is ThemeListingDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('downloads' in value) || value['downloads'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('author' in value) || value['author'] === undefined) return false;
    return true;
}

export function ThemeListingDtoFromJSON(json: any): ThemeListingDto {
    return ThemeListingDtoFromJSONTyped(json, false);
}

export function ThemeListingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeListingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'downloads': json['downloads'],
        'version': json['version'],
        'name': json['name'],
        'author': json['author'],
    };
}

export function ThemeListingDtoToJSON(value?: ThemeListingDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'downloads': value['downloads'],
        'version': value['version'],
        'name': value['name'],
        'author': value['author'],
    };
}

