/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeUpdateRequestDto
 */
export interface ThemeUpdateRequestDto {
    /**
     * The theme id of the updated theme
     * @type {string}
     * @memberof ThemeUpdateRequestDto
     */
    newId: string;
}

/**
 * Check if a given object implements the ThemeUpdateRequestDto interface.
 */
export function instanceOfThemeUpdateRequestDto(value: object): value is ThemeUpdateRequestDto {
    if (!('newId' in value) || value['newId'] === undefined) return false;
    return true;
}

export function ThemeUpdateRequestDtoFromJSON(json: any): ThemeUpdateRequestDto {
    return ThemeUpdateRequestDtoFromJSONTyped(json, false);
}

export function ThemeUpdateRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeUpdateRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'newId': json['newId'],
    };
}

export function ThemeUpdateRequestDtoToJSON(value?: ThemeUpdateRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'newId': value['newId'],
    };
}

