/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThemeShareDto
 */
export interface ThemeShareDto {
    /**
     * Public theme id / share
     * @type {string}
     * @memberof ThemeShareDto
     */
    id: string;
}

/**
 * Check if a given object implements the ThemeShareDto interface.
 */
export function instanceOfThemeShareDto(value: object): value is ThemeShareDto {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ThemeShareDtoFromJSON(json: any): ThemeShareDto {
    return ThemeShareDtoFromJSONTyped(json, false);
}

export function ThemeShareDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThemeShareDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function ThemeShareDtoToJSON(value?: ThemeShareDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

