/* tslint:disable */
/* eslint-disable */
/**
 * Skribbl Typo API
 * Skribbl Typo API for resources, admin tools and authentification.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateDiscordID
 */
export interface UpdateDiscordID {
    /**
     * The id of the new linked discord account
     * @type {string}
     * @memberof UpdateDiscordID
     */
    id: string;
}

/**
 * Check if a given object implements the UpdateDiscordID interface.
 */
export function instanceOfUpdateDiscordID(value: object): value is UpdateDiscordID {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UpdateDiscordIDFromJSON(json: any): UpdateDiscordID {
    return UpdateDiscordIDFromJSONTyped(json, false);
}

export function UpdateDiscordIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDiscordID {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function UpdateDiscordIDToJSON(value?: UpdateDiscordID | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

